[package]
name = "askeladd"
version.workspace = true
edition.workspace = true

[dependencies]
stwo-prover.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.62"
config = "0.14.0"
dotenv = "0.15"
